/*
CREATE SCHEMA COMPANY;
USE COMPANY;
*/


CREATE TABLE EMPLOYEE(
	Fname VARCHAR(15) NOT NULL,
	Minit CHAR,
	Lname VARCHAR(15) NOT NULL,
	Ssn CHAR(9) NOT NULL,
	Bdate DATE,
	Address VARCHAR(30),
	Sex CHAR,
	Salary DECIMAL(10,2),
	Super_ssn CHAR(9),
	Dno INT,
	CONSTRAINT EMPPK
		PRIMARY KEY(Ssn));

CREATE TABLE DEPARTMENT(
	Dname	VARCHAR(15)	NOT NULL,
	Dnumber	INT		NOT NULL CHECK(Dnumber>0),
	Mgr_ssn	CHAR(9),
	Mgr_start_date	DATE	,
	CONSTRAINT DEPTPK
		PRIMARY KEY(Dnumber),
	CONSTRAINT DEPTSK
		UNIQUE(Dname));
	
CREATE TABLE DEPT_LOCATIONS(
	Dnumber	INT	NOT NULL,
	Dlocation	VARCHAR(15)	NOT NULL,
	CONSTRAINT DEPTLOCPK
		PRIMARY KEY(Dnumber, Dlocation));

CREATE TABLE PROJECT(
	Pname	VARCHAR(15)	NOT NULL,
	Pnumber	INT	NOT NULL CHECK(Pnumber>0),
	Plocation	VARCHAR(15),
	Dnum		INT,
	CONSTRAINT PRJPK
		PRIMARY KEY(Pnumber),
	CONSTRAINT PRJSK
		UNIQUE(Pname));

CREATE TABLE WORKS_ON(
	Essn		CHAR(9)	NOT NULL,
	Pno		INT		NOT NULL,
	Hours	DECIMAL(5,1),
	CONSTRAINT WRKONPK
		PRIMARY KEY(Essn, Pno));

CREATE TABLE DEPENDENT(
	Essn		CHAR(9)	NOT NULL,
	Dependent_name	VARCHAR(15)	NOT NULL,
	Sex		CHAR	,
	Bdate	DATE,
	Relationship		VARCHAR(15)	NOT NULL,
	CONSTRAINT DEPENPK
		PRIMARY KEY(Essn, Dependent_name));
	
	
ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMPSUPERFK FOREIGN KEY(Super_ssn) REFERENCES EMPLOYEE(Ssn)
			ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMPDEPTFK FOREIGN KEY(Dno) REFERENCES DEPARTMENT(Dnumber)
			ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE DEPARTMENT
ADD CONSTRAINT DEPTMGRFK FOREIGN KEY(Mgr_ssn) REFERENCES EMPLOYEE(Ssn)
			ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE DEPT_LOCATIONS
ADD CONSTRAINT DEPTLOCFK FOREIGN KEY(Dnumber) REFERENCES DEPARTMENT(Dnumber)
			ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PROJECT
ADD CONSTRAINT PRJFK FOREIGN KEY(Dnum, Plocation) REFERENCES DEPT_LOCATIONS(Dnumber, Dlocation)
			ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE WORKS_ON
ADD CONSTRAINT WRKONSsnFK FOREIGN KEY(Essn) REFERENCES EMPLOYEE(Ssn)
			ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE WORKS_ON
ADD CONSTRAINT WRKONPrjFK FOREIGN KEY(Pno) REFERENCES PROJECT(Pnumber)
			ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE DEPENDENT
ADD CONSTRAINT DEPENFK FOREIGN KEY(Essn) REFERENCES EMPLOYEE(Ssn)
			ON DELETE CASCADE ON UPDATE CASCADE;







/*
SHOW DATABASES; -> show all the databases in the server. USE <database_name>; -> start using specified database . SHOW TABLES; -> show tables inside the selected database. DESCRIBE <table_name>; -> show information on a specified table SELECT * FROM <table_name>; -> show all attributes of all tuples in a table


*/
